# Configure the build matrix
language: php
php:
  - 5.3
before_install:
  - sudo apt-get update
  - sudo apt-get install php5-cgi libapache2-mod-fastcgi apache2-suexec-custom
  - sudo a2enmod actions fastcgi suexec
  - sudo cp php-fcgi.conf /etc/apache2/sites-enabled
  - sudo /etc/init.d/apache2 restart
script:
  - wget -O - http://localhost/test.php
after_script:
  - sudo cat /var/log/apache2/access_log
  - sudo cat /var/log/apache2/error_log
  - ls /var/www
  - ls /home/travis
  - ls /etc/apache2/sites-enabled
