# Configure the build matrix
language: php
php:
  - 5.3
before_install:
  # Install Apache2, FastCGI, and PHP
  - sudo apt-get update
  - sudo apt-get install php5-cgi libapache2-mod-fastcgi apache2-suexec-custom apache2-mpm-prefork

  # Enable the FastCGI and suEXEC modules
  - sudo a2enmod actions fastcgi suexec
  - sudo cp php-fcgi.conf /etc/apache2/sites-enabled
  - ls /etc/apache2/suexec
  - cat /etc/apache2/suexec/*
  - sudo sed -i -e "s,/var/www,$(pwd)/,g" /etc/apache2/suexec/www-data
  - sudo sed -i -e "s,/var/www,$(pwd)/,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,\${APACHE_LOG_DIR},$(pwd),g" /etc/apache2/sites-available/default
  - sudo cp --preserve cgi-bin/php.fcgi /usr/lib/cgi-bin
  - cat /etc/apache2/suexec/www-data
  - sudo /etc/init.d/apache2 restart
script:
  - wget -O - http://localhost
  - wget -O - http://localhost/test.php
after_script:
  - sudo cat access.log
  - sudo cat error.log
  - sudo cat /var/log/apache2/suexec.log
  - cat /etc/apache2/sites-enabled/000-default
  - ls /etc/apache2
  - ls /etc/apache2/conf.d
  - cat /etc/apache2/conf.d/*
  - cat /etc/apache2/httpd.conf
