# Configure the build matrix
language: php
php:
  - 5.3
before_install:
  - sudo apt-get update
  - sudo apt-get install php5-cgi libapache2-mod-fastcgi apache2-suexec-custom apache2-mpm-prefork
  - sudo a2enmod actions fastcgi suexec
  - sudo cp php-fcgi.conf /etc/apache2/sites-enabled
  - sudo sed -i -e "s,/var/www,$(pwd)/,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,\${APACHE_LOG_DIR},$(pwd),g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,/var/www,$(pwd)/,g" /etc/apache2/sites-enabled/php-fcgi.conf
  - sudo cp --preserve cgi-bin/php.fcgi /usr/lib/cgi-bin
  - ls -ls /usr/lib/cgi-bin
  - sudo /etc/init.d/apache2 restart
script:
  - wget -O - http://localhost
  - wget -O - http://localhost/test.php
  - wget -O - http://localhost/phpinfo.php
after_script:
  - sudo cat access.log
  - sudo cat error.log
  - ls /var/www
  - ls /home/travis
  - ls /etc/apache2/sites-enabled
  - cat /etc/apache2/sites-enabled/000-default
