language: php
php:
  - 5.3

before_install:
  - sudo apt-get update
  - sudo apt-get install php5-cgi libapache2-mod-fastcgi apache2-suexec-custom apache2-mpm-prefork

  # Configure Apache/FastCGI/suPHP
  - sudo a2enmod actions fastcgi suexec
  - |
      echo "Action application/x-httpd-php /cgi-bin/php.fcgi
      SuexecUserGroup travis travis" | sudo tee /etc/apache2/sites-enabled/php-fcgi.conf
  - mkdir -m 755 cgi-bin
  - |
      echo "#!/bin/sh
      export PHP_FCGI_CHILDREN=4
      export PHP_FCGI_MAX_REQUESTS=200
      exec /usr/bin/php5-cgi" > cgi-bin/php.fcgi
  - sudo sed -i -e "s,#FastCgiWrapper /usr/lib/apache2/suexec,FastCgiWrapper /usr/lib/apache2/suexec,g" /etc/apache2/mods-enabled/fastcgi.conf
  - sudo sed -i -e "s,/var/www,$(pwd),g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,/usr/lib/cgi-bin,$(pwd)/cgi-bin,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,\${APACHE_LOG_DIR},$(pwd),g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,/var/www,$(pwd)/,g" /etc/apache2/suexec/www-data
  - sudo chmod -R g-w cgi-bin
  - sudo /etc/init.d/apache2 restart

script:
  # Call the test script to output the current user. Should be "travis".
  - wget -O - -q http://localhost/test.php
