# Configure the build matrix
language: php
php:
  - 5.3
before_install:
  # Install Apache2, FastCGI, and PHP
  - sudo apt-get update
  - sudo apt-get install php5-cgi libapache2-mod-fastcgi apache2-suexec-custom apache2-mpm-prefork

  # Enable the FastCGI and suEXEC modules
  - sudo a2enmod actions fastcgi suexec
  - sudo cp php-fcgi.conf /etc/apache2/sites-enabled
  # Configure Apache
  - cat /etc/apache2/mods-enabled/fastcgi.conf
  - sudo sed -i -e "s,#FastCgiWrapper /usr/lib/apache2/suexec,FastCgiWrapper /usr/lib/apache2/suexec,g" /etc/apache2/mods-enabled/fastcgi.conf
  - cat /etc/apache2/mods-enabled/fastcgi.conf
  - sudo sed -i -e "s,/var/www,$(pwd),g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,/usr/lib/cgi-bin,$(pwd)/cgi-bin,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,\${APACHE_LOG_DIR},$(pwd),g" /etc/apache2/sites-available/default

  # Configure suEXEC
  - sudo sed -i -e "s,/var/www,$(pwd)/,g" /etc/apache2/suexec/www-data

  # Restart Apache2 with the new configuration
  - sudo /etc/init.d/apache2 restart
script:
  - wget -O - http://localhost
  - wget -O - http://localhost/test.php
after_script:
  - sudo cat access.log
  - sudo cat error.log
  - sudo cat /var/log/apache2/suexec.log
  - cat /etc/apache2/suexec/www-data
  - cat /etc/apache2/sites-enabled/000-default
